pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

tutorialcadastro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Local
    path("", include("pages.urls", namespace="pages")),
]

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    bio = models.TextField(blank=True)

users/forms.py
from django.contrib.auth import forms

from .models import User


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://www.freeiconspng.com/thumbs/csgo-icon/counter-strike-global-offensive-csgo-icon-8.png" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-primary mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Início</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}CS COMUNITY{% endblock %}

{% block content %}

    <h1 style="text-align:center;">Comunidade de CSGO</h1>
    <br> </br>
    <h3>Intro</h3>
    <p>Seja bem-vindo a nossa comunidade de <b>CS:GO.</b> Pra você que está iniciando no competitivo ou você que já conhece o jogo mas é ruim pra car*lho.
    Na nossa comunidade você vai aprender, noções básicas como o uso de cada arma, economia, situações de jogo...
    Pare de culpar seus companheiros de time pela sua incapacidade e seja um player melhor.</p>  
    <iframe width="640" height="360" src="https://www.youtube.com/embed/X4lbt7rkz9o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <br> </br>
    <h4>Economia</h4>
    <p>Economia no CS é uma coisa muito importante, já dizia Dilma Rousseff. Aprendendo a controlar bem a economia sua e de seu time, tenha certeza que seu jogo irá melhorar. Sendo assim, vamos ao básico do básico.</p>

        <p>Todo round ganho por matar o time inimigo ou pelo relógio (CT), todos do time ganham $3250. Todo round ganho por C4, sendo explodido (TR) ou defusado (CT), todos do time ganham $3500. E se o C4 for plantado mas defusado, o time TR ganha um bônus de $800</p>
        
        <p>Quando o time perde um round pela 1ª vez, ganha $1400. Na 2ª vez, $1900. Na 3ª vez, $2400. Na 4ª vez, $2900. Do 5º round em diante, $3400.</p>
        
        <p>Por isso é bom ficar ligado no placar da partida. Se seu time ganhar 4-5 rounds seguidos, perder o próximo e logo em seguida ganhar, vocês resetaram a economia do inimigo. Então, se prepare para um rush (pistolas), um forçado bem sem vergonha ou um filho da p*ta marotado te esperando de Zeus. Compre pelo menos uma granada incendiária/molotov e HE para travar e punir o rush deles e verifique cada canto em que avançar.</p>
        <a href="https://www.youtube.com/watch?v=_gy_5zKxuWE">Como saber o básico da economia</a>
        <br> </br>
    <h4>1 Round(Pistol)</h4> 
    <p><b>CT</b></p>
    <ul>
        <li>Compre colete, ou outra pistola e granadas ou até mesmo defuse</li>
        <li>Não compre smoke, pois ela não vai segurar rush neste round</li>
        
      </ul>
      <p><b>TR</b></p>
      <ul>
        <li>Compre colete ou uma pistola e granada(s)</li>
        <li>Se você nunca consegue matar alguém no pistol, dê preferência para comprar granadas. Smoke e duas flashs ou molotov e smoke. As flashs e smoke irão ajudar na entrada do bomb e o molotov vai ser útil para atrasar o retake dos CTs ou até mesmo evitar que o C4 seja defusado</li>
        
      </ul>  
      <a href="https://www.youtube.com/watch?v=_1k2RhgnaL8">Como melhorar no pistol.</a>
      <br> </br>
      <h3>Situações de jogo.</h3>
      <ul>
        <li>De CT, definam a posição de cada um. Se ver que mesmo assim um retardad0 está indo marcar junto onde já está "cheio", mude você de posição. No próximo round, avise e troque</li>
        <li>De TR, <b>combinem uma estratégia</b> no começo ou trabalhem e decidam durante o round</li>
        <li>Sempre avise onde está indo. Seja de CT ou TR</li>
        <li>Morreu? <b>Passe informação daquilo que você viu.</b> Onde aconteceu, localização, quantidade de inimigos, arma(s)...</li>
        <li>Já passou as informações necessárias aos companheiros? Agora cala a boca. É a vez dele de jogar. Ficar falando, mesmo que seja sobre a situação, vai atrapalhar mais do que ajudar. <b>Não fique narrando a performance do seu companheiro</b></li>
        <li>Não comece o round jogando todas as suas granadas. Use-as com consciência. Um molotov ou HE numa situação de afterplant é mais do que bem-vindo</li>
        <li><b>É clutch? SEGURE SHIFT ATÉ O INIMIGO DESCOBRIR SUA POSIÇÃO.</b>  Não recarregue (só se tiver certeza que o inimigo está longe), não puxe granada (mesma situação de recarregar)... Agora é hora de focar, não fazer barulho, escutar tudo. Se alguém de casa pedir socorro, ignore</li>
        <li>Saiba quando usar a faca. Início de round, após atirar e fugir... <b>Não ande com a faca na mão simplesmente por andar.</b> Você pode dar de cara com o inimigo, e até puxar a arma, já vai estar lamentando. A pistola te permite uma velocidade próxima e também a reação com poder de fogo</li>
        <li><b>Não fique perdido no mapa, mongando</b> enquanto seus companheiros estão decidindo uma entrada. Mire num lugar, cubra as costas deles, faça a função de lurker...</li>

      </ul>
      <br> </br>
      <h3>Melhorando seu jogo</h3>  
      <ul>
        <li>Tenha noção do spray das armas que você mais usa. Não atire contando somente com a sorte</li>
        <li>Aqueça antes! Seja num DM ou mapa customizado. Aqueça seu spray, reflexo, tempo de reação...
        </li>
        
      </ul> 
      <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=419404847">Mapa para melhorar spray e recoil</a>
      <br> </br>
      <h3>Glossário e acrônimos</h3>
      <ul>
        <li><b>Afterplant:</b> Período após o C4 ser plantado</li>
        <li><b>Away:</b> Jogador ausente. Geralmente cumprindo uma tarefa da mãe</li>
        <li><b>Awper:</b> Jogador de AWP</li>
        <li><b>Backup / back:</b> Solicitação de reforço do CT para aquela área</li>
        <li><b>Bangar:</b> Atirar uma flash ou ato sexual</li>
        <li><b>Bombsite / bomb:</b> A ou B. Os lugares de plantar o C4</li>
        <li><b>C4:</b> Bomba que os terroristas precisam plantar</li>
        <li><b>Camper:</b> Jogador com o teclado quebrado</li>
        <li><b>Clutch:</b> Situação sob pressão onde você está sozinho contra o(s) inimigo(s)
            Colete1: Colete (B-5-1)</li>
        <li><b>Cover:</b> Solicitação de proteção para vigiar determinada área (geralmente costas)</li>
        <li><b>Eco:</b> Round econômico</li>
      </ul>
      <h5>Veja de uma forma mais detalhada as gírias nesse vídeo</h5>
      <iframe width="640" height="360" src="https://www.youtube.com/embed/7oa2XOTngxc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <br> </br>
      <br> </br>
      <h5>Passe no guia de onde tirei a maioria desse conteúdo.</h5>>
      <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=805090716">Guia do básico do cs.</a>

    <h5>E também passe no meu github! <a href="https://github.com/robinhosz">Meu GitHub</a>.</h5>
    

    <body style="background-color:  lightgray">

        
        
        </body>
{% endblock %}